config/routes.rb
Rails.application.routes.draw do

  root 'lcls#new'
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#logout'
  post '/lcls/register'
  resources :lcls, except: [:index, :destroy]
  resources :consignees, only: [:new, :create, :show, :edit, :update]

end

app/models/consignee.rb
class Consignee < ActiveRecord::Base
  # before_create :format_phone
  has_many :lcls
  has_many :containers, through: :lcls

  validates :name, :phone, :email, presence: true
  validates :name, uniqueness: true
  has_secure_password

  # def format_phone
    
  # end
end

app/models/container.rb
class Container < ActiveRecord::Base
  has_many :lcls
  has_many :consignees, through: :lcls
  validates :container_number, presence: true, uniqueness: true
end

app/models/lcl.rb
class Lcl < ActiveRecord::Base
  belongs_to :container
  belongs_to :consignee
  validates :consignee, :description, :dest_lat, :dest_long, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_filter :ensure_login, only: [:create, :show, :edit, :destroy]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  def current_user
    @consignee ||= Consignee.find_by(id: session[:consignee_id])
  end

  def logged_in?
    !!current_user
  end

  private
  def ensure_login
    redirect_to root_path unless logged_in?
  end

  protect_from_forgery with: :exception
end

app/controllers/consignees_controller.rb
class ConsigneesController < ApplicationController
  skip_before_action :ensure_login, only: :create
  def new
    @consignee = Consignee.new
    render '_form'
  end

  def create
    @consignee = Consignee.new(consignee_params)
    if @consignee.save
      session[:consignee_id] = @consignee.id
      redirect_to @consignee
    else
      @errors = @consignee.errors.full_messages
      render '_form'
    end
  end

  def show
    @consignee = Consignee.find_by(id: params[:id])
    verify_authorized
    @lcls = @consignee.lcls
  end

  def edit
    @consignee = Consignee.find_by(id: params[:id])
    verify_authorized
    render '_form'
  end

  def update
    @consignee = Consignee.find_by(id: params[:id])
    verify_authorized
    if @consignee.update(consignee_params)
      redirect_to @consignee
    else
      @errors = @consignee.errors.full_messages
      render '_form'
    end
  end

  private
  def consignee_params
    params.require(:consignee).permit(:name, :phone, :email, :password, :password_confirmation)
  end

  def verify_authorized
    redirect_to root_path unless current_user == @consignee
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
end

app/controllers/lcls_controller.rb
class LclsController < ApplicationController
  def new
    @lcl = Lcl.new
  end

  def create
    @lcl = Lcl.new(lcl_params)
    @lcl.consignee = current_user
    if @lcl.save
      redirect_to @lcl
    else
      @errors = @lcl.errors.full_messages
      render 'new'
    end
  end

  def show
    @lcl = Lcl.find_by(id: params[:id])
    verify_authorized
  end

  def edit
    @lcl = Lcl.find_by(id: params[:id])
    verify_authorized
    render '_form'
  end

  def update
    @lcl = Lcl.find_by(id: params[:id])
    verify_authorized
    if @lcl.update(lcl_params)
      redirect_to @lcl
    else
      @errors = @lcl.errors.full_messages
      render '_form'
    end
  end

  def register
    lcl = Lcl.find_by(id: params[:lcl_id])
    consignee = lcl.consignee
    # This is where the lcl will be associated with a container
    response = Unirest.post("", 'headers' : {'accept' : 'application/json','content-type'  : 'application/json'},
      'parameters' : {'token' : '4c6e5658457074684162456e464f5a476d55654361477a5753677373584952694e79786568776f4f676e6162', 'phone_numbers' : "347-720-9741 9176033714 9176965027"})
    response.code
  end

  def arrived
    # This is where the consignee will be notified of arrival in port
    # A container id will come in in the post request and all relevant LCLs will be notified
  end

  private
  def lcl_params
    params.require(:lcl).permit(:description, :destination_name, :dest_lat, :dest_long)
  end

  def verify_authorized
    redirect_to root_path unless current_user == @lcl.consignee
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_login, only: :create
  def login
  end

  def create
    @consignee = Consignee.find_by(name: params[:name])
    if @consignee && @consignee.authenticate(params[:password])
      session[:consignee_id] = @consignee.id
      redirect_to root_path
    else
      @errors = ["Incorrect name or password"]
      render "login"
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consignees_helper.rb
module ConsigneesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/lcls_helper.rb
module LclsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/consignees/_form.html.erb
<%= form_for @consignee do |f| %>
  <div>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label "Phone Number" %>
    <%= f.text_field :phone, placeholder: 'Format: ##########' %>
  </div>
  <div>
    <%= f.label "E-mail Address" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label "Password" %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>
<%= render 'layouts/errors' %>

app/views/consignees/show.html.erb
<div>
  <%= @consignee.name %>
</div>
<div>
  <%= @consignee.phone %>
</div>
<div>
  <%= @consignee.email %>
</div>
<div>
  <%= link_to "Edit", edit_consignee_path(@consignee) %>
</div>

<% if @lcls %>
  <ul>
  <% @lcls.each do |cargo| %>
    <li><%= link_to cargo.description, cargo %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_errors.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LCLEnterprises</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>LCL Enterprises</h1>
    <%= link_to "Home", root_path %> | 
    <% if logged_in? %>
      <%= link_to current_user.name, consignee_path(current_user) %> | <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", login_path %> | <%= link_to "Sign up", new_consignee_path %>
    <% end %>
  </header>

<%= yield %>

</body>
</html>

app/views/lcls/_form.html.erb
<%= form_for @lcl do |f| %>
  <div>
    <%= f.label "Description" %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label "Name of Destination Port" %>
    <%= f.text_field :destination_name %>
  </div>
  <div>
    <%= f.label "Latitude of Destination Port" %>
    <%= f.text_field :dest_lat %>
  </div>
  <div>
    <%= f.label "Longitude of Destination Port" %>
    <%= f.text_field :dest_long %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>
<%= render 'layouts/errors' %>

app/views/lcls/new.html.erb
<% if logged_in? %>
  <%= render 'form' %>
<% else %>
  <h2>Please <a href="/login">Log in</a></h2>
<% end %>

app/views/lcls/register.html.erb
<h1>You have done a thing! Yay!</h1>

app/views/lcls/show.html.erb
<h2>Thank you, your cargo has been registered</h2>

<div>
  <p>
    Your cargo is:
  </p>
  <p>
    <%= @lcl.description %>
  </p>
  <p>
    It is being shipped to:
  </p>
  <p>
    <%= @lcl.destination_name %>
  </p>
  <p>
    at <%= @lcl.dest_lat %>, <%= @lcl.dest_long %>
  </p>
  <p>
    If any of this is incorrect, please <%= link_to "edit it", edit_lcl_path(@lcl) %> now.
  </p>
</div>